Repository jenkins-x-charts/prow, pull requests merged in 2018-11, with the labels that each got.

#18 fix: crier is starting/running nicely
  prow/templates/crier-role.yaml
  prow/values.yaml
Labels: approved

#16 fix: removed references to depreacted chartmuseum instance
  prow/Makefile
Labels: approved, size/XS

#19 feat(buildnum): Add helm charts for jx controller buildnumbers.
  prow/templates/_helpers.tpl
  prow/templates/buildnum-deployment.yaml
  prow/templates/buildnum-service.yaml
  prow/values.yaml
Labels: approved, size/M

#20 feat: Use specific name for jx tag so that updatebot can update it.
  prow/templates/buildnum-deployment.yaml
  prow/values.yaml
Labels: approved, size/XS
