Repository jenkins-x-charts/prow, pull requests merged in 2018-12, with the labels that each got.

#22 add missing build resources and increase start liveness checks to give more time for worker caches to sync
  prow/templates/build-deployment.yaml
  prow/values.yaml
Labels: approved, size/XS

#23 feat: removing tot service, using buildnum instead
  prow/templates/_helpers.tpl
  prow/templates/tot-deployment.yaml
  prow/templates/tot-pvc.yaml
  prow/templates/tot-service.yaml
  prow/values.yaml
Labels: approved, size/M

#25 fix: add 'patch' verb
  prow/templates/crier-clusterrole.yaml
Labels: approved, lgtm, ok-to-test, size/XS
