Repository jenkins-x-charts/prow, pull requests merged in 2019-02, with the labels that each got.

#152 fix: lets enable buildnum to watch pipeline activities
  prow/templates/buildnum-role.yaml
Labels: approved, size/XS

#153 switch to jenkinsxio images
  prow/values.yaml
Labels: approved, size/M

#154 fix: add missing pipelinerunner.name
  prow/templates/_helpers.tpl
Labels: approved, size/XS

#157 fix deck after prow rebase
  prow/values.yaml
Labels: approved, size/S

#165 bump prow to fix displaying results
  prow/values.yaml
Labels: approved, size/S

#222 bump prow version that includes fixes for pipeline runner
  prow/values.yaml
Labels: approved, size/S

#227 add missing pipeline roles
  prow/templates/pipelinerunner-role.yaml
Labels: approved, size/M

#229 default pipeline builds to use the pipeline build bot service account
  prow/values.yaml
Labels: approved, size/XS

#238 bump prow tag
  prow/values.yaml
Labels: approved, size/S

#258 rename build pipeline to tekton
  prow/templates/pipeline-clusterrole.yaml
  prow/values.yaml
Labels: approved, size/S

#266 rename pipeline > tekton
  prow/templates/pipeline-clusterrole.yaml
  prow/templates/pipelinerunner-role.yaml
  prow/values.yaml
Labels: approved, size/S

#274 lets use builder-maven for pipelinerunner
  prow/values.yaml
Labels: approved, size/XS

#275 fix: use tag for the image tag for pipeline runner
  prow/templates/pipelinerunner-deployment.yaml
  prow/values.yaml
Labels: approved, size/XS

#277 fix: allow pipelinerunner to create PipeilneStructures
  prow/templates/pipelinerunner-role.yaml
Labels: approved, size/XS

#279 fix: add pipelinerunner env vars
  prow/templates/pipelinerunner-deployment.yaml
  prow/values.yaml
Labels: approved, size/S

#280 chore: tone down maven download logging
  prow/values.yaml
Labels: approved, size/XS

#282 fix: let pipelinerunner reuse git secrets
  prow/templates/pipelinerunner-role.yaml
Labels: approved, size/XS
