Repository jenkins-x-charts/prow, pull requests merged in 2019-04, with the labels that each got.

#422 fix: roles for pipelinerunner
  prow/templates/pipelinerunner-role.yaml
Labels: approved, size/XS

#368 feat: tempalte the prow components image
  prow/templates/branchprotector-cj.yaml
  prow/templates/build-deployment.yaml
  prow/templates/crier-deployment.yaml
  prow/templates/deck-deployment.yaml
  prow/templates/hook-deployment.yaml
  prow/templates/horologium-deployment.yaml
  prow/templates/pipeline-deployment.yaml
  prow/templates/plank-deployment.yaml
  prow/templates/sinker-deployment.yaml
  prow/templates/tide-deployment.yaml
  prow/values.yaml
Labels: approved, lgtm, size/M

#441 add missing patch role for environments
  prow/templates/pipelinerunner-role.yaml
Labels: approved, size/XS

#437 Configure properly the readiness and liveness probes for deck
  prow/templates/deck-deployment.yaml
  prow/values.yaml
Labels: approved, size/S

#460 lets try a new PR to see if that triggers prow job
  prow/values.yaml
Labels: approved, size/XS

#459 chore: upgrade prow images tag with the fix for Job URL
  prow/values.yaml
Labels: approved, lgtm, size/XS

#470 chore: update the prow images tag
  prow/templates/pipeline-clusterrole.yaml
  prow/values.yaml
Labels: approved, size/XS

#483 fix: lets make prow-build optional
  prow/templates/build-clusterrole.yaml
  prow/templates/build-clusterrolebinding.yaml
  prow/templates/build-deployment.yaml
  prow/templates/build-sa.yaml
  prow/values.yaml
Labels: size/S

#496 feat: added datadog annotations to prow chart
  prow/templates/build-deployment.yaml
  prow/templates/buildnum-deployment.yaml
  prow/templates/crier-deployment.yaml
  prow/templates/deck-deployment.yaml
  prow/templates/hook-deployment.yaml
  prow/templates/horologium-deployment.yaml
  prow/templates/pipeline-deployment.yaml
  prow/templates/pipelinerunner-deployment.yaml
  prow/templates/plank-deployment.yaml
  prow/templates/sinker-deployment.yaml
  prow/templates/tide-deployment.yaml
Labels: approved, size/S

#498 feat: allowing enabling/disabling of datadog annotations
  prow/templates/build-deployment.yaml
  prow/templates/buildnum-deployment.yaml
  prow/templates/crier-deployment.yaml
  prow/templates/deck-deployment.yaml
  prow/templates/hook-deployment.yaml
  prow/templates/horologium-deployment.yaml
  prow/templates/pipeline-deployment.yaml
  prow/templates/pipelinerunner-deployment.yaml
  prow/templates/plank-deployment.yaml
  prow/templates/sinker-deployment.yaml
  prow/templates/tide-deployment.yaml
  prow/values.yaml
Labels: approved, size/M

#501 fix: update to latest builders
  prow/values.yaml
Labels: approved, size/XS

#557 fix: re-enable json logging
  prow/values.yaml
Labels: approved, size/XS
