Repository jenkins-x-charts/prow, pull requests merged in 2019-01, with the labels that each got.

#27 rebase the Jenkins X fork to bring latest upstream fixes
  prow/templates/build-deployment.yaml
  prow/values.yaml
Labels: approved, size/S

#91 lets allow access to namespaces
  prow/templates/buildnum-role.yaml
Labels: approved, size/XS

#103 latest prow updates
  prow/values.yaml
Labels: approved, size/XS

#104 fix sinker error after bad image rename
  prow/values.yaml
Labels: approved, size/S

#93 feat: add tide dashboard and installed plugins
  prow/values.yaml
Labels: approved, size/XS

#26 fix: using Release.Namespace in the ClusterRoleBinding name
  prow/templates/build-clusterrolebinding.yaml
  prow/templates/clusterrolebinding.yaml
  prow/templates/crier-clusterrolebinding.yaml
Labels: approved, size/S

#134 feat: add liveness & readiness probes for build number service.
  prow/templates/buildnum-deployment.yaml
  prow/values.yaml
Labels: approved, size/S

#139 add pipeline controller
  prow/values.yaml
Labels: approved, size/M

#140 add pipeline name to helm helper
  prow/templates/_helpers.tpl
Labels: approved, size/XS

#141 add missing pipeline yamls
  prow/templates/pipeline-clusterrole.yaml
  prow/templates/pipeline-clusterrolebinding.yaml
  prow/templates/pipeline-deployment.yaml
  prow/templates/pipeline-sa.yaml
  prow/values.yaml
Labels: approved, size/M

#142 avoid tmp liveness checks now rebase means controllers start up nicely
  prow/templates/build-deployment.yaml
Labels: approved, size/S

#143 lets avoid rolling out latest prow changes
  prow/templates/_helpers.tpl
  prow/templates/build-deployment.yaml
  prow/templates/pipeline-clusterrole.yaml
  prow/templates/pipeline-clusterrolebinding.yaml
  prow/templates/pipeline-deployment.yaml
  prow/templates/pipeline-sa.yaml
  prow/values.yaml
Labels: approved, size/L
