Repository jenkins-x-charts/prow, pull requests merged in 2019-07, with the labels that each got.

#875 fix: allow pipelinerunner to access apps resources
  prow/templates/pipelinerunner-role.yaml
Labels: approved, lgtm, size/XS

#878 chore: add release notes
  Makefile
Labels: approved, size/XS

#889 chore(deps): bump jenkins-x/jenkins-x-builders to 0.1.564
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  prow/values.yaml
Labels: size/S, updatebot

#890 chore(deps): bump jenkins-x/jenkins-x-builders to 0.1.564
  prow/values.yaml
Labels: size/XS, updatebot

#976 fix: increasing memory limit for pipelinerunner
  prow/values.yaml
Labels: approved, lgtm, size/XS
